FROM node:20.14.0-alpine3.20 as builder

ADD . /app

WORKDIR /app

RUN npm install

RUN npm run build

RUN wget https://gobinaries.com/tj/node-prune --output-document - | /bin/sh && node-prune

FROM node:20.14.0-alpine3.20

COPY --from=builder /app/node_modules /app/node_modules

COPY --from=builder /app/package*.json /app/

COPY --from=builder /app/dist /app/dist

WORKDIR /app

EXPOSE 3000

CMD ["npm", "run", "test"]